-
  version: 3.2.0-pre-{build}
  image: Visual Studio 2017  
  pull_requests:
    do_not_increment_build_number: true
  branches:
    only:
    - dev
  configuration: Release
  dotnet_csproj:
    patch: false
  before_build:
    - dotnet restore
    - ps: ./appveyor.ps1
  build:
    publish_nuget: true
    verbosity: minimal
  environment:
    api_key:
      secure: 9+5MJ4M65M1G/0Kqcy6KQ1huc/kc23m/GVDcvflLKYC2dtfWdQ2DiDSoO7hd6Tnm
  deploy_script:
    - ps: ($artifacts.values | Where-Object {($_.path -like '*.nupkg') -and  !($_.path -like '*.symbols.nupkg')}) | foreach-object { write-host $_.path; dotnet nuget push $_.path -s https://www.nuget.org/api/v2/package -k $env:api_key; if ($lastexitcode -ne 0) {throw}}

-
  image: Visual Studio 2017
  pull_requests:
    do_not_increment_build_number: true
  branches:
    only:
    - master
  configuration: Release
  before_build:
    - dotnet restore
  dotnet_csproj:
    patch: false
  build:
    publish_nuget: true
    verbosity: minimal
  environment:
    api_key:
      secure: 9+5MJ4M65M1G/0Kqcy6KQ1huc/kc23m/GVDcvflLKYC2dtfWdQ2DiDSoO7hd6Tnm
  deploy_script:
    - ps: ($artifacts.values | Where-Object {($_.path -like '*.nupkg') -and  !($_.path -like '*.symbols.nupkg')}) | foreach-object { write-host $_.path; dotnet nuget push $_.path -s https://www.nuget.org/api/v2/package -k $env:api_key; if ($lastexitcode -ne 0) {throw}}
